language: ruby
rvm:
- jruby
- 2.0.0
- 1.9.3
notifications:
  email: false
  hipchat:
    rooms:
      secure: Qtz0eyDiNlnikRWy8rM7mm4yYEz510B/URR6uY7YzEefyGeTDJqAp2CTexIwlKshw4tAgnZvlvk77BJCjD+2M6JGx5qj1p3NlOnkui+DeJ6izgRArRhWCf/V46IbQffmRplZJp2kD2cocKmDOriORKH30cUITEYWsunEZqQ+BqM=
